server:
  port: 8080

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://db:5432/payment
    username: ${POSTGRESQL_USER_NAME:user}
    password: ${POSTGRESQL_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

services:
  authorization-service: https://run.mocky.io/v3/91c7417a-a8d0-486f-bca2-a46473c2e37e