server:
  port: 8080

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:payment
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true